gems:
- jekyll-redirect-from
- jekyll-sitemap
- algoliasearch-jekyll

# ---
# Define URLs
# ---
url: https://plot.ly
BASE_URL: https://plot.ly
staticurl: https://plot.ly/gh-pages/documentation/static/

# ---
# Excludes
# ---
#exclude: ['*.Rmd','_posts/2015-09-09-matlab-reference.html','_posts/2015-09-06-r-reference.html','_posts/2015-09-06-python-reference.html','_posts/2015-08-19-plotly_js-reference.html','_posts/2015-04-05-ggplot2-index.html','_posts/2015-04-05-julia-index.html','_posts/2015-04-05-matplotlib-index.html','_posts/2015-04-05-node_js-index.html','_posts/2015-04-05-plotly_js-index.html','_posts/2015-04-05-plotlyjs-function-reference.md','_posts/2015-05-25-ipython-notebooks_gallery.html','_posts/2015-05-25-ipython-notebooks_index.html','_posts/2015-07-13-eula_index.html','_posts/2015-07-19-pandas.html','_posts/2015-07-26-index.html','_posts/2015-07-30-r-index.Rmd','_posts/2015-07-30-r-index.md','_posts/2015-08-20-research-box-index.html','_posts/ggplot2','_posts/julia','_posts/matplotlib','_posts/nodejs','_posts/pandas','_posts/plotly_js','_posts/r','_posts/tutorials','_posts/user_guide_python']
exclude: [_posts/temp, '*.Rmd', _posts/user_guide_python/old_user_guide/redirect_from]

# ---
# Algolia Search
# ---
# Plotly_js Search
# update js_docs search index with: make update_js_search
#

algolia:
  application_id: '7EK9KHJW8M'
  index_name:     'js_docs'
  read_only_api_key: '4dae07ded6a721de73bde7356eec9280'
  excluded_files:
    - '*.json'
    - '*.ipynb'
    - '*.md'
    - '*.R'
    - '*.Rmd'
    - '_posts/dashboards'
    - '_posts/ggplot2'
    - '_posts/ipython-notebooks'
    - '_posts/julia'
    - '_posts/matlab'
    - '_posts/matplotlib'
    - '_posts/misc'
    - '_posts/nodejs'
    - '_posts/numpy'
    - '_posts/pandas'
    - '_posts/plotly_js/.DS_Store'
    - '_posts/plotly_js/examples'
    - '_posts/python'
    - '_posts/r'
    - '_posts/reference_pages'
    - '_posts/scala'
    - '_posts/scikit'
    - '_posts/temp'
    - '_posts/2015-07-26-index.html'
  settings:
    attributesToIndex:
      - name
      - description
      - title
