gems:
- octopress-debugger
- jekyll-redirect-from
- jekyll-sitemap

site: https://plot.ly
baseurl: https://plot.ly
BASE_URL: https://plot.ly
staticurl: https://plot.ly/gh-pages/documentation/static/

