gems:
- jekyll-redirect-from
- jekyll-sitemap

# ---
# Define URLs
# ---
url: https://plot.ly
BASE_URL: https://plot.ly
staticurl: https://plot.ly/gh-pages/documentation/static/

# ---
# Assets
# ---
imgurl: https://images.plot.ly/plotly-documentation/
stylesheet: https://s3-us-west-1.amazonaws.com/plotly-tutorials/assets/css/api/main.css
plotlyjs_download_url: https://cdn.plot.ly/plotly-latest.min.js


# ---
# Excludes
# ---
exclude: [_posts/temp, '*.Rmd']

# ---
# Markdown / Syntax
# ---
kramdown:
  input: GFM
markdown: redcarpet
redcarpet:
  extensions: ["tables", "fenced_code_blocks"]
