staticurl: http://localhost:4000/all_static
# [ggplot2, julia, matlab, matplotlib, nodejs, plotly_js, python, r, tutorials, user_guide_matlab, user_guide_python, user_guide_r]
exclude: [_posts/ggplot2, _posts/julia, _posts/matlab, _posts/matplotlib, _posts/nodejs, _posts/plotly_js, _posts/python, _posts/r, _posts/tutorials, _posts/user_guide_matlab, _posts/user_guide_r]
